// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DueDateSnapShot } from "./DueDateSnapShot";

export interface DueDateInfo { unit_snapshots: Array<DueDateSnapShot>, }