// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterestSnapShot } from "./InterestSnapShot";

export interface InterestInfo { total_interests: number, unit_snapshots: Array<InterestSnapShot>, }