// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unit } from "./Unit";

export interface LeftIncomeSnapShot { unit: Unit, first_date: string, last_budget_date: string, amount: number, number: number, }