// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeftIncomeSnapShot } from "./LeftIncomeSnapShot";

export interface LeftIncomeInfo { total_income: number, unit_snapshots: Array<LeftIncomeSnapShot>, }