// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentSnapShot } from "./PaymentSnapShot";

export interface PaymentInfo { total_payment: number, unit_snapshots: Array<PaymentSnapShot>, }