// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitBudget { id: string, unitId: string, budgetDate: string, budget: number, isSelf: boolean, }