// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitBudgetForUpdate { unit_id?: string, budget_date?: string, budget?: number, is_self?: boolean, }