// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitForUpdate { name?: string, isLunar?: boolean, lastBiddedDate?: string, day?: bigint, cycle?: bigint, plusDay?: bigint, plusCycle?: bigint, budget?: bigint, count?: bigint, biddedCount?: bigint, unitCount?: bigint, amount?: bigint, description?: string, }