// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitTime { date: string, num: number, budget: number | null, last_budget: number | null, }