// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitForUpdate { name?: string, is_lunar?: boolean, last_bidded_date?: string, day?: bigint, cycle?: bigint, plus_day?: bigint, plus_cycle?: bigint, budget?: bigint, count?: bigint, bidded_count?: bigint, unit_count?: bigint, amount?: bigint, description?: string, }