// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitBudget } from "./UnitBudget";

export interface Unit { id: string, name: string, isLunar: boolean, lastBiddedDate: string, day: bigint, cycle: bigint, plusDay: bigint | null, plusCycle: bigint | null, budget: bigint, count: bigint, biddedCount: bigint, unitCount: bigint, amount: bigint | null, description: string | null, unitBudgets: Array<UnitBudget | null> | null, }