// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitBudgetForCreate } from "./UnitBudgetForCreate";

export interface UnitForCreate { name: string, isLunar: boolean, lastBiddedDate: string, day: number, cycle: number, plusDay: number, plusCycle: number, budget: number, count: number, biddedCount: number, unitCount: number, amount?: number, description?: string, unitBudgets?: Array<UnitBudgetForCreate>, }