// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitBudgetForCreate } from "./UnitBudgetForCreate";

export interface UnitForCreate { name: string, is_lunar: boolean, last_bidded_date: string, day: number, cycle: number, plus_day?: number, plus_cycle?: number, budget: number, count: number, bidded_count: number, unit_count: number, amount?: bigint, description?: string, unit_budgets?: Array<UnitBudgetForCreate>, }