// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitBudget } from "./UnitBudget";

export interface Unit { id: string, name: string, isLunar: boolean, lastBiddedDate: string, day: number, cycle: number, plusDay?: number, plusCycle?: number, budget: number, count: number, biddedCount: number, unitCount: number, amount?: number, description?: string, unitBudgets?: Array<UnitBudget | null>, }