// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnitBudgetForUpdate { unitId?: string, budgetDate?: string, budget?: bigint, budget1?: number, isSelf?: boolean, }